/**
 * Build-time sitemap from published CMS fallback slugs (TASK-074 / indexing).
 * Run: npm run generate:sitemap
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { fallbackBlogPosts } from '../src/content/fallback/blogPosts.ts'
import { fallbackCaseStudies } from '../src/content/fallback/caseStudies.ts'
import { fallbackServices } from '../src/content/fallback/services.ts'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.resolve(__dirname, '..', 'public', 'sitemap.xml')

const SITE = (process.env.VITE_SITE_URL ?? 'https://www.roseng.org').replace(/\/$/, '')

const STATIC_ROUTES = [
  { loc: '/', changefreq: 'weekly', priority: '1.0' },
  { loc: '/services', changefreq: 'weekly', priority: '0.9' },
  { loc: '/about', changefreq: 'monthly', priority: '0.8' },
  { loc: '/insights', changefreq: 'weekly', priority: '0.8' },
  { loc: '/case-studies', changefreq: 'weekly', priority: '0.8' },
  { loc: '/contact', changefreq: 'monthly', priority: '0.9' },
  { loc: '/schedule', changefreq: 'monthly', priority: '0.8' },
]

function publishedSlugRoutes(items, prefix, changefreq, priority) {
  return items
    .filter((item) => item.status === 'published')
    .map((item) => ({
      loc: `${prefix}/${item.slug}`,
      changefreq,
      priority,
    }))
}

const routes = [
  ...STATIC_ROUTES,
  ...publishedSlugRoutes(fallbackServices, '/services', 'monthly', '0.8'),
  ...publishedSlugRoutes(fallbackBlogPosts, '/insights', 'monthly', '0.7'),
  ...publishedSlugRoutes(fallbackCaseStudies, '/case-studies', 'monthly', '0.7'),
]

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- Brand: RoseJS · Domain: ${SITE} — generated by scripts/generate-sitemap.mjs -->
${routes
  .map(
    (r) => `  <url>
    <loc>${SITE}${r.loc === '/' ? '/' : r.loc}</loc>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`,
  )
  .join('\n')}
</urlset>
`

writeFileSync(OUT, `${xml}\n`, 'utf8')
console.log(`Wrote ${routes.length} URLs to ${OUT}`)
